micronaut:
  application:
    name: customer-service
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

redis:
  uri: redis://localhost

endpoints:
  health:
    enabled: true

jackson:
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: 'jdbc:postgresql://ec2-35-169-188-58.compute-1.amazonaws.com:5432/dekpul6hhqcjji'
    username: 'ogncvzqlhdppim'
    password: '10e394d5460f970a4e548ccd6b9cdd1b05e00cddcc8ea8a166188d83f1a07c56'
    driverClassName: 'org.postgresql.Driver'
    initialSize: 2
    minIdle: 2
    maxIdle: 5
    maxActive: 10

jpa:
  default:
    packages-to-scan:
      - 'br.com.leavecargo.customer.domain.model'
    properties:
      hibernate:
        physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
        hbm2ddl:
          auto: none
        show_sql: false

app:
  service:
    zone-id: America/Sao_Paulo
  controller:
    page-size: 100
